php/util.php
[Here](https://github.com/webfactory/slimdump/blob/7125abe60164397c506dc451137855791088e984/src/Webfactory/Slimdump/Database/Dumper.php#L109) we're setting PDO attributes for the DB connection to work with buffered queries. 
We should assert that the underlying connection is in fact PDO, otherwise this call will fail.
Also, [this line](https://github.com/webfactory/slimdump/blob/7125abe60164397c506dc451137855791088e984/php/util.php#L11) is probably supposed to use PDO as the driver, but it seems passing DSNs like `mysqli://...` will override the setting.
=> Make sure we're using PDO

src/Webfactory/Slimdump/Database/Dumper.php
This may happen if you're dumping big tables. Seems the MySQL server pushes the data over to the client (being in "writing to net state" for quite some time), but then may switch to "sleep" state while the libmysqlclient in PHP is still reading the data and/or slimdump is writing it to disk.
If `wait_timeout` is short, the MySQL server may close the connection before we issue the next query. This change will make sure the connection is alive before querying for data or table structures.
=> Reconnect if MySQL server has gone away

composer.json, composer.lock, src/Webfactory/Slimdump/Database/Dumper.php
If `OutputInterface::OUTPUT_RAW` is not added, the strings to be written will be passed through output processors that will do some fancy replacements/addtions. That greatly increases the memory footprint so we avoid it.
=> Use OutputInterface::OUTPUT_RAW to reduce memory consumption

README.md, src/Webfactory/Slimdump/Config/Table.php, src/Webfactory/Slimdump/Database/Dumper.php, src/Webfactory/Slimdump/SlimdumpCommand.php, test/Webfactory/Slimdump/Config/TableTest.php
We're using `SHOW CREATE TABLE` to get the table creation SQL, but that includes the `AUTO_INCREMENT` value (at least for some storage engines).
Depending on the use case, it would be nice to be able to get rid of that.
=> Add option to avoid dumping AUTO_INCREMENT values

src/Webfactory/Slimdump/Config/FakerReplacer.php, test/Webfactory/Slimdump/Config/FakerReplacerTest.php
Hey guys,
I saw that "name" is already (is it new, I never saw it before?! :D) an "official" faker formatter.
So I deleted the self-written formatter. 
I decided to keep the configuration skeleton because I am sure we will need individual stuff in the further development of slimdump.
=> add-faker-integration: removed 'name' because it is an existing faker option

README.md, src/Webfactory/Slimdump/Config/Table.php, src/Webfactory/Slimdump/Database/Dumper.php, src/Webfactory/Slimdump/SlimdumpCommand.php, test/Webfactory/Slimdump/Config/TableTest.php, test/Webfactory/Slimdump/Database/DumperTest.php
This will include `CREATE TRIGGER ...` statements when dumping a table. Dumping at `schema` level is sufficient to dump the triggers as well.
If you would like to skip (all) triggers for a table, add `<table ... dump-triggers="false" />` to your config.
Trigger creation statements will be placed after the `INSERT` statements for the table in question, I hope that makes sense.
The `` DEFINER=`user`@`host` `` clause will always be stripped from the `CREATE TRIGGER` statement to make re-importing the dump as another user easier.
Closes #26.
*ping* @MalteWunsch
=> Support dumping triggers

box.json.dist
Unfortunately the generation of the .phar package does not work very well. These small adjustments should do the trick.
=> Fix configuration for .phar generation

README.md, composer.lock, src/Webfactory/Slimdump/Config/Column.php, src/Webfactory/Slimdump/Config/FakerReplacer.php, test/Webfactory/Slimdump/Config/ColumnTest.php
Added support for Faker modifiers, such as "unique". Allows to replace database values with fake values, which are unique per column.
=> Support Faker modifiers (such as unique)

README.md, src/Webfactory/Slimdump/Config/Table.php, src/Webfactory/Slimdump/Database/Dumper.php, src/Webfactory/Slimdump/SlimdumpCommand.php
We had some problems inserting some huge tables, so we added a limit for the buffer size.
=> Add buffer-size limitation to table config

src/Webfactory/Slimdump/SlimdumpCommand.php
I didn't want to give up the parsing of the DSN string by the DriverManager so I chose to replace the 'mysqli://' in the connection string with 'mysql://' if it exists, this way we should always end up with a PDO Connection.
If we would do the parsing ourselves then we could skip the 'url' Parameter in DriverManager::getConnection($params).
Any connection information inside $params['url'] will always precede other parameters, see https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/DriverManager.php#L400
Fixes #44 
DBAL Docs on creating a Connection: https://www.doctrine-project.org/projects/doctrine-dbal/en/2.7/reference/configuration.html
=> Force PDO Connection for mysqli DSN by 'cleaning' the connection string

src/Webfactory/Slimdump/Database/Dumper.php
In our project, it is not possible to count all rows in our biggest table (very bad performances) before exporting a small subset of this table.
We need to apply the same condition as the one in the XML configuration file which for some reason is ignored when estimating the number of rows that will be exported.
=> Apply `WHERE` condition when counting the number of rows to export

src/Webfactory/Slimdump/Database/Dumper.php
- Fix Travis CI build. And it's about changing `implode` function usage.
The deprecated message about `implode` function is as follows:
```
1) Webfactory\Slimdump\Database\DumperTest::testDumpDataWithFullConfiguration
implode(): Passing glue string after array is deprecated. Swap the parameters
/home/travis/build/webfactory/slimdump/src/Webfactory/Slimdump/Database/Dumper.php:226
```
=> Fix Travis CI about implode function usage

composer.json
- The `PSR-0` autoloading is deprecated. Using the `PSR-4` approach instead.
=> Using PSR-4 autoloading instead

README.md
- According to the useful [reference](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository), adding the GitHub actions badge to replace Travis CI build status badge.
=> Add GitHub action badge link

README.md, src/Webfactory/Slimdump/Database/Dumper.php, src/Webfactory/Slimdump/DumpTask.php, src/Webfactory/Slimdump/SlimdumpCommand.php
We have noticed that extended inserts with a large amount of data can run significantly faster if they do not contain newlines ("`\n`"). To make this behavior available in Slimdump, we introduce the `--single-line-insert-statements` option.
To ensure BC, this option defaults to FALSE.
=> Add option to write INSERT statements to one single line (Case 109924)

src/Webfactory/Slimdump/DumpTask.php, src/Webfactory/Slimdump/SlimdumpCommand.php
As pointed out in #64, the feature of controlling the buffer size (introduced in [f227b13..141d02b](https://github.com/webfactory/slimdump/compare/f227b133cea2296e4399a4307b39be2f60ef0027..141d02bca66c648aa1003face6d0a28ddac29835)) got lost during the merge of [f227b13..fe193d0](https://github.com/webfactory/slimdump/compare/f227b133cea2296e4399a4307b39be2f60ef0027..fe193d0b6ecf4a5fe312e0d08019a694b30d421f). This PR reintroduces the lost changes, and it seems to work fine.
=> Repair --buffer-size parameter

src/Webfactory/Slimdump/SlimdumpCommand.php
A possible mitigation for #84, but maybe also an addition helpful in general:
Since dumping (large) tables might take some time, it might be reasonable and helpful to the user if we disable the [`max_execution_time` MySQL timeout setting](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_max_execution_time) for the current connection.
=> Disable MySQL's `max_execution_time` timeout if set

src/Webfactory/Slimdump/Database/Dumper.php
This might be a sufficient mitigation for #84.
Might give false alarms to users that are not really affected by #84, but who try to `slimpdump` tables while rows are being added and/or deleted in between counting and dumping the rows (currently, no transaction support in `slimdump`).
=> Print a warning when the number of rows dumped does not match the expected count

.github/workflows/dependencies.yml, .github/workflows/release.yml, .github/workflows/tests.yml
Der für uns wesentliche Unterschied sollte die Verwendung von MySQL 8 sein. Auf diese Weise können wir testen, ob wir vorwärtskompatibel sind.
=> Führe GitHub Actions Workflows mit Ubuntu 20.04 aus

.github/workflows/dependencies.yml, .github/workflows/fix-cs-php.yml, .github/workflows/release.yml, .github/workflows/tests.yml, composer.json, composer.lock, src/Webfactory/Slimdump/Database/Dumper.php
Update the test matrix to run also PHP 8.x while dropping compatibility with really old package versions.
Update `composer.lock` (used when building the boxed .phar version) using PHP 7.4.
=> Bump dependencies, update test matrix

src/Webfactory/Slimdump/Database/Dumper.php, src/Webfactory/Slimdump/Database/OutputFormatDriverInterface.php, src/Webfactory/Slimdump/Database/SqlDumper.php, src/Webfactory/Slimdump/SlimdumpCommand.php
This PR tweaks the new `SqlDumper` class from #88 a bit and introduces a dedicated interface for it. Also, it prefers using the Schema Tool API instead of passing around an array of column names.
=> Extract OutputFormatDriverInterface and clean up its method signatures by preferring passing Schema Asset objects

src/Webfactory/Slimdump/Database/Dumper.php
The `Connection::ping()` method is deprecated in Doctrine DBAL.
According to the deprecation notice, "retry and reconnecting lost connections now happens automatically".
Thus, we can remove the `keepalive()` method.
=> Remove the `Dumper::keepalive()` method

.github/workflows/php-version-compatibility.yml, composer.json, composer.lock
Downgrade dependencies to versions compatible with PHP ^7.2, and add a workflow to check if the composer.lock file works for different PHP versions.
We need to declare `symfony/service-contracts` `^2.1.2` to come up with dependency versions compatible with PHP 7.2 – 8.1.
=> Ensure PHP 7.2 compatibility for the `composer.lock` file

README.md, src/Webfactory/Slimdump/Database/CsvOutputFormatDriver.php, src/Webfactory/Slimdump/SlimdumpCommand.php
This PR implements a new output mode for CSV files.
The new command option `--output-csv=...` enables CSV output mode, and must be given the path to a directory. The output mode will create `.csv` files in the given directory, named according to the dumped tables.
This output format does not support output redirection from `stdout` as the default MySQL SQL format does.
CSV files will be created only for tables that contain data. In other words, `schema` type dumps will skip the table in question. Also, dumping views/triggers makes no sense for CSV files, they will be skipped as well.
How to best write binary (BLOB) data and/or NULL values in CSV files is probably highly controversial. For now, we'll just go with the [`0x...` hex literals supported by …
=> Implement CSV output mode

src/Webfactory/Slimdump/Database/CsvOutputFormatDriver.php, src/Webfactory/Slimdump/Database/Dumper.php, src/Webfactory/Slimdump/Database/MysqlOutputFormatDriver.php, src/Webfactory/Slimdump/Database/OutputFormatDriverInterface.php
When the new CSV output mode with the concept of "output drivers" was added in #92, dumping `TRIGGER` definitions was made an implementation detail of the MySQL output driver. This caused `TRIGGER` definitions to be dumped right after the `CREATE TABLE ...` commands, before the actual data `INSERT` statements.
This potentially breaks the generated SQL files, since a newly created trigger may be relevant for the subsequent `INSERT` statements; however, MySQL requires that tables used in the trigger are also included in the `LOCK TABLES` statements.
The aim of this PR is to revert that change, i. e. to dump trigger definitions for a table _after_ the data insert statements for it.
I think it is not necessary to move all trigger definitions to the very end of the output – that is, after …
=> Dump TRIGGER definitions _after_ data

composer.json, composer.lock, src/Webfactory/Slimdump/Doctrine/DoctrineSubscriber.php, src/Webfactory/Slimdump/Doctrine/DummyType.php, src/Webfactory/Slimdump/Doctrine/DummyTypeRegistrationEventSubscriber.php, src/Webfactory/Slimdump/SlimdumpCommand.php
We're using the `SchemaManager` to simplify listing tables, views and so on. But, the information provided by it also includes the DBAL types used for columns, and that information may be parsed from column comments in the database.
The problem is that a table definition like so:
```sql
CREATE TABLE `test` (
`some_col` int NOT NULL COMMENT '(DC2Type:some_type)'
)
```
... `slimdump` fail fail with an exception because it does not know about the `some_type`. This type may be available and defined in your application, but we cannot put it into the `slimdump` command.
Now, in fact, we don't care about the type and its conversion capabilities at all. So, this PR adds a runtime "just in type" registration of a `DummyType` that serves as a placeholder to avoid issues when loading the schema. …
=> Fill in dummy types to deal with DC2:... column comments

.github/workflows/php-version-compatibility.yml, .github/workflows/release.yml, .github/workflows/tests.yml, composer.json, composer.lock
This only keeps support for PHP 8.1+, the lowest (security fix) supported version as of today.
=> Drop support for old PHP versions and update dependencies accordingly
